FROM node:20-slim as deps

WORKDIR /app

COPY package.json ./
COPY yarn.lock ./
RUN yarn --check-files

FROM node:20-slim as builder

WORKDIR /app

ADD . .
COPY --from=deps /app/node_modules/ /app/node_modules/
COPY --from=deps /app/package.json /app/yarn.lock  /app/
CMD ["yarn", "dev"]
